import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CFG } from '@/data/site';
import { Media, Reveal, SectionHeading } from './shared';
const filters=['Todos','Residencial','Institucional','Infraestrutura'] as const;
type Project=(typeof CFG.projects)[number];
export function Lightbox({project,onClose}: {project:Project|null,onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;if(project){el?.showModal()}else{el?.close()}},[project]);useEffect(()=>{const el=ref.current;const onCancel=(e:Event)=>{e.preventDefault();onClose()};el?.addEventListener('cancel',onCancel);return()=>el?.removeEventListener('cancel',onCancel)},[onClose]);return <dialog ref={ref} onClick={e=>{if(e.target===ref.current)onClose()}} className="m-auto w-[min(94vw,920px)] max-w-none border-0 bg-card p-0 text-card-foreground backdrop:bg-deep/85"><div className="relative"><Button variant="navy" size="icon" className="absolute right-3 top-3 z-10" aria-label="Fechar imagem" onClick={onClose}><X/></Button>{project&&<><img src={project.image} alt={`Imagem ilustrativa: ${project.title}`} className="aspect-[4/3] max-h-[75vh] w-full object-contain bg-deep"/><div className="p-5"><span className="text-xs font-bold uppercase text-ocean">{project.category} · Imagem ilustrativa</span><h3 className="mt-1 text-xl font-extrabold">{project.title}</h3><p className="mt-1 text-sm text-muted-foreground">{project.description}</p></div></>}</div></dialog>}
export function Projects(){const [filter,setFilter]=useState<(typeof filters)[number]>('Todos'),[selected,setSelected]=useState<Project|null>(null);const list=filter==='Todos'?CFG.projects:CFG.projects.filter(p=>p.category===filter);return <section id="projetos" className="section-pad bg-soft"><div className="wrap"><Reveal><SectionHeading tag="Projetos" title="Projetos que deixam sua marca."/></Reveal><div className="mt-9 flex flex-wrap gap-2" role="group" aria-label="Filtrar projetos">{filters.map(f=><Button key={f} variant={filter===f?'navy':'navyOutline'} aria-pressed={filter===f} onClick={()=>setFilter(f)} className="min-h-11 px-4 text-xs sm:px-6">{f}</Button>)}</div>{list.length?<div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{list.map((p,i)=><Reveal key={p.title} delay={(i%3)*90}><Button variant="ghost" onClick={()=>setSelected(p)} aria-label={`Ampliar ${p.title}, imagem ilustrativa`} className="group block h-auto w-full overflow-hidden rounded-none border-0 bg-card p-0 text-left shadow-sm transition-shadow hover:bg-card hover:shadow-lg"><div className="relative aspect-[4/3] overflow-hidden"><Media image={p.image} video={p.video} alt={`Imagem ilustrativa: ${p.title}`} className="absolute inset-0 transition-transform duration-500 group-hover:scale-[1.06]"/><div className="project-gradient absolute inset-0"/><span className="absolute left-4 top-4 bg-gold px-2 py-1 text-[10px] font-bold text-gold-foreground">Imagem ilustrativa</span><span className="absolute bottom-5 right-5 flex items-center gap-1 text-xs font-bold text-on-dark opacity-0 transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100">Ampliar <ArrowUpRight size={15}/></span></div><div className="p-6"><span className="text-[10px] font-extrabold uppercase tracking-widest text-ocean">{p.category}</span><h3 className="mt-2 text-lg font-extrabold text-foreground">{p.title}</h3><p className="mt-2 whitespace-normal text-sm font-normal leading-relaxed text-muted-foreground">{p.description}</p></div></Button></Reveal>)}</div>:<div className="mt-10 border border-border bg-card px-6 py-14 text-center text-muted-foreground">Ainda não há projetos publicados nesta categoria.</div>}<p className="mt-7 text-xs leading-relaxed text-muted-foreground">Imagens ilustrativas de banco de imagens. Os projetos reais da F Dois Engenharia serão publicados aqui.</p></div><Lightbox project={selected} onClose={()=>setSelected(null)}/></section>}
